pipeline {
    agent{
        docker{
           image 'maven:3.6.1-jdk-8-slim'
           args '-v $HOME/.m2:/root/.m2'
        }
    }

   stages {
      stage('build') {
        when {
            changeset "java/cmad-ms-users/*"
        }
         steps {
            echo "Compiling users service"
            dir('java/cmad-ms-users'){
               sh 'mvn compile'
            }        
         }
      }
      stage('test') {
         when {
            changeset "java/cmad-ms-users/*"
         }
         steps {
            echo "Running unit tests on users service"
            dir('java/cmad-ms-users'){
               sh 'mvn clean test'
            }
         }
      }
      stage('package') {
         when { 
            changeset "java/cmad-ms-users/*"
            branch "master"     
         }
         steps {
            echo "Packaging users app"
            dir('java/cmad-ms-users'){
               sh 'mvn package -DskipTests'
            }
            archiveArtifacts 'java/cmad-ms-users/target/*.jar'
         }
      }
   }
}